name: Update plugin assets/readme on WordPress.org
on:
  push:
    branches:
      - master
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin assets/readme update
        uses: 10up/action-wordpress-plugin-asset-update@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mark-posts
